version: "3"
services:
  app:
    container_name: app
    restart: always
    image: hanzkid/prasmul-be
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"